name: Bug report
description: File a bug report
title: "Bug: "
labels:
  - bug-candidate
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a potential bug in `pip-audit`!

        Please read the following parts of this form carefully.
        Invalid or incomplete submissions will be given a lower priority or
        closed outright.

  - type: checkboxes
    attributes:
      label: Pre-submission checks
      description: |
        By submitting this issue, you affirm that you've satisfied the following conditions.
      options:
        - label: >-
            I am **not** filing an auditing error (false positive or negative).
            These **must** be reported to
            [pypa/advisory-database](https://github.com/pypa/advisory-database/issues/new) instead.
          required: true
        - label: >-
            I agree to follow the [PSF Code of Conduct](https://www.python.org/psf/conduct/).
          required: true
        - label: >-
            I have looked through the open issues for a duplicate report.
          required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        I expected `pip-audit ...` to do X, Y, and Z.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: |
        Instead of doing X, Y, and Z, `pip-audit ...` produced got the following error: ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction steps
      description: A step-by-step list of actions that we can take to reproduce the actual behavior.
      placeholder: |
        1. Do this
        2. Do that
        3. Do another thing
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      description: |
        If applicable, please paste any logs or console errors here.

        If you can re-run the command that produced the error, run it with
        `--verbose` and paste the full verbose logs here.
      render: plain text

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other additional context about the problem here.

  - type: input
    attributes:
      label: OS name, version, and architecture
      placeholder: Mac OS X 10.4.11 on PowerPC

  - type: input
    attributes:
      label: pip-audit version
      description: |
        `pip-audit -V`
    validations:
      required: true

  - type: input
    attributes:
      label: pip version
      description: |
        `pip -V` or `pip3 -V`
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      description: |
        `python -V` or `python3 -V`
    validations:
      required: true
